version: '3'

services:
  secure-nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - RTMP_PORT=1935
      - AUTH_KEY=123456789
      # specify a domain here, so run lets-encrypt for generating a cert
      # - DOMAIN_NAME=mydomain.com
      - ENABLE_720P_2628KBS=FALSE
      - ENABLE_480P_1128KBS=TRUE
      - ENABLE_360P_878KBS=TRUE
      - ENABLE_240P_528KBS=FALSE
      - ENABLE_240P_264KBS=FALSE
      # specify a certificate here if you specified a domain and do not want to use lets-encrypt
      # - CERT_PRIVATE_KEY=example.com.key
      # - CERT_PUBLIC=example.com.crt
    volumes:
      - ./certs:/opt/certs
      - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt:
