version: '3'

services:
  secure-nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - RTMP_PORT=1935
      - AUTH_KEY=123456789
      - DOMAIN_NAME=mydomain.com
      - ENABLE_720P_2628KBS=TRUE
      - ENABLE_480P_1128KBS=TRUE
      - ENABLE_360P_878KBS=TRUE
      - ENABLE_240P_528KBS=TRUE
      - ENABLE_240P_264KBS=TRUE
    volumes:
      - ./certs:/opt/certs
